# Generated by Django 4.2.8 on 2023-12-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
